### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Ellimistdev** [Ellimistdev/mastermind#1]
**Needed Logic**
- [x] Code generation
- [x] Attempt validation
- [x] Introduction
- [x] Game engine (ongoing method for duration of game)
- [x] Victory condition checking
- [x] Game end actions

**Improvements**
- [x] Replace color and key strings with pretty representations
- [x] Make Board.display look like a real game board
- [ ] Testing!

**Nice to have**
- [ ] Ability to be codemaker
- [ ] 2 player
